<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>AvalonMarkdown</PackageId>
    <Version>5.0.0</Version>
    <Title>AvalonMarkdown</Title>
    <Authors>Axvser</Authors>
    <Description>NativeWebView based Markdown preview control for AvaloniaUI.</Description>
    <PackageTags>avalonia;markdown;webview;preview</PackageTags>
    <PackageIcon>Assets\logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/Axvser/AvalonMarkdown</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Axvser/AvalonMarkdown.git</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Remove="Assets\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Controls.WebView" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="True" PackagePath="\" />
    <None Include="Assets\logo.png" Pack="True" PackagePath="Assets\" />
  </ItemGroup>
</Project>
